version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 9000:80
      - 9004:443
    volumes:
      - ./data:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx:/www